{
 "title": "Synology Status",
 "description": "Panel for Synology metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "default_interval", "label": "Interval", "query": "30s,1m,5m,30m,1h,12h" },
   {
    "name": "nas_host",
    "label": "NAS",
    "query": "SHOW TAG VALUES FROM \"synology_system\" WITH KEY = \"nas_name\""
   },
   {
    "name": "nas_interface",
    "label": "Interface",
    "query": "SHOW TAG VALUES FROM \"synology_network\" WITH KEY = \"interface_name\"  WHERE \"nas_name\" =~ /^$nas_host/"
   },
   {
    "name": "nas_disk",
    "label": "Disk",
    "query": "SHOW TAG VALUES FROM \"synology_disk\" WITH KEY = \"disk_path\" WHERE \"nas_name\" =~ /^$nas_host/"
   },
   {
    "name": "nas_volume",
    "label": "Volume",
    "query": "SHOW TAG VALUES FROM \"synology_raid\" WITH KEY = \"raid_name\" WHERE \"nas_name\" =~ /^$nas_host/"
   },
   { "name": "volume_interval", "label": "Volume Interval", "query": "7d,14d,30d,60d,90d,180d,365d" }
  ]
 },
 "panels": [
  {
   "title": "$nas_host Overview",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "synology_system",
     "select": [
      [
       { "params": [ "system_temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Temperature" ], "type": "alias" }
      ],
      [
       { "params": [ "system_status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "System Status" ], "type": "alias" }
      ],
      [
       { "params": [ "fan_status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Fan Status" ], "type": "alias" }
      ],
      [
       { "params": [ "upgrade_status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Upgrade Status" ], "type": "alias" }
      ],
      [
       { "params": [ "dsm_version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "DSM Version" ], "type": "alias" }
      ],
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/ 100" ], "type": "math" },
       { "params": [ "Uptime" ], "type": "alias" }
      ],
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Model" ], "type": "alias" }
      ],
      [
       { "params": [ "serial_number" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Serial Number" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nas_name", "operator": "=~", "value": "/^$nas_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Resource Stats",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syno_snmp",
     "query": "SELECT 100 - mean(\"usage_idle\") FROM \"synology_cpu\" WHERE \"nas_name\" =~ /^$nas_host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu_free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$nas_host$/" },
      { "condition": "AND", "key": "stat", "operator": "=", "value": "nas_cpu" }
     ]
    },
    {
     "alias": "Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"system_temp\") FROM \"synology_system\" WHERE \"nas_name\" =~ /^$nas_host$/  AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Mem",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ((mean(\"mem_total\") - mean(\"mem_avail_real\") - mean(\"mem_buffer\") - mean(\"mem_cached\"))/mean(\"mem_total\") * 100)  FROM \"synology_memory\" WHERE \"nas_name\" =~ /^$nas_host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$nas_interface Interface Rx/Tx Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface_name:$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "synology_network",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nas_name", "operator": "=~", "value": "/^$nas_host$/" },
      { "condition": "AND", "key": "interface_name", "operator": "=~", "value": "/^$nas_interface$/" }
     ]
    }
   ]
  },
  {
   "title": "$nas_disk Disk IO Rates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_disk_path:$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk_path" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "synology_disk",
     "select": [
      [
       { "params": [ "disk_reads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "disk_writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nas_name", "operator": "=~", "value": "/^$nas_host$/" },
      { "condition": "AND", "key": "disk_path", "operator": "=~", "value": "/^$nas_disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Information",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "disk_name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "synology_disk",
     "select": [
      [
       { "params": [ "disk_status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Status" ], "type": "alias" }
      ],
      [
       { "params": [ "disk_model" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Model" ], "type": "alias" }
      ],
      [
       { "params": [ "disk_type" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Type" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nas_name", "operator": "=~", "value": "/^$nas_host$/" }
     ]
    }
   ]
  },
  {
   "title": "$nas_volume Volume Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_raid_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "drive" ], "type": "tag" }
     ],
     "measurement": "syno_snmp",
     "query": "SELECT ((mean(\"raid_total_size\") - mean(\"raid_free_size\"))/ mean(\"raid_total_size\")) * 100  FROM \"synology_raid\" WHERE \"nas_name\" =~ /^$nas_host$/ AND \"raid_name\" =~ /^$nas_volume$/ AND $timeFilter GROUP BY  time($__interval), \"raid_name\"  fill(none)",
     "select": [
      [
       { "params": [ "drive_temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Temp" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$nas_host$/" },
      { "condition": "AND", "key": "stat", "operator": "=", "value": "nas_volumes" },
      { "condition": "AND", "key": "volume", "operator": "=~", "value": "/^$nas_volume$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume Information",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "volume" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "syno_snmp",
     "query": "SELECT \"raid_total_size\" / 1024 / 1024 / 1024 AS \"Size\", (\"raid_total_size\" - \"raid_free_size\") / 1024 / 1024 / 1024 AS \"Used\",  \"raid_free_size\" / 1024 / 1024 / 1024 AS \"Free\" FROM \"synology_raid\" WHERE \"nas_name\" =~ /^$nas_host$/ AND $timeFilter GROUP BY  \"raid_name\" LIMIT 1",
     "select": [
      [
       { "params": [ "vol_totalsize" ], "type": "field" },
       { "params": [ "Volume Size" ], "type": "alias" }
      ],
      [
       { "params": [ "vol_used" ], "type": "field" },
       { "params": [ "Used" ], "type": "alias" }
      ],
      [
       { "params": [ "vol_used" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$nas_host$/" },
      { "condition": "AND", "key": "stat", "operator": "=", "value": "nas_volumes" }
     ]
    }
   ]
  }
 ]
}